
### GET 示例
GET http://localhost:8000/

### POST 示例
POST http://localhost:8000/items/
Content-Type: application/json

{
  "q": "FastAPI 测试"
}

### PUT 示例

PUT http://localhost:8000/items/123
Content-Type: application/json

{
    "item": {
        "name": "python",
        "desc": "",
        "price": 12.88,
        "tax": 1.35
    }
}

###
DELETE  http://localhost:8000/items/1
Content-Type: application/json


